### ISSUE TITLE
Error: Cannot find module '@bolt/twig-renderer'

### ISSUE THREAD

**Issue by a-fro** [bolt-design-system/bolt#1092]
First of all, I'm really excited to see what you've done with Bolt! It's exactly the kind of setup we were looking for. I'm trying to run the "Drupal Lab" example implementation to get to know all the moving parts. I'm able to successfully complete `composer run setup` if I run the setup within a compiled and working version of the design system itself (this repo). However, I've tried integrating the setup into several other working projects (one based on a custom project, and another based simply on the composer version of Drupal lab. In both cases, `composer run setup` leads to the following error output: 

```
[aaron@mbp ~/sites/bolt.drupal.test/web/themes/bolt-starter]$ npm run build

> @bolt/bolt-starter@2.2.2 build /Users/aaron/sites/bolt.drupal.test/web/themes/bolt-starter
> bolt build --prod


    ///////|\\\\\\
   ///˜˜˜˜/|˜˜˜˜\\\
  ///    //|     \\\     Bolt-CLI
 ///    ///|____  \\\
///    /////////   \\\   Welcome to the Bolt CLI ⚡️  Have fun!
\\\   /////////    ///
 \\\      |///    ///    Usage: `bolt <command> [options ...]`
  \\\     |//    ///     Help: `bolt --help` or `bolt <command> --help`
   \\\____|/____///
    \\\\\\|///////

Starting build (serial)
Verbosity: 1
Prod: true
i18n: true
(node:48378) UnhandledPromiseRejectionWarning: Error: Cannot find module '@bolt/twig-renderer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/aaron/sites/bolt.drupal.test/web/themes/bolt-starter/node_modules/@bolt/build-tools/api/index.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/aaron/sites/bolt.drupal.test/web/themes/bolt-starter/node_modules/@bolt/build-tools/tasks/webpack-tasks.js:9:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
(node:48378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:48378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please advise. Thanks!

**Comment by a-fro** [comment]
I was able to resolve the issue with `npm -i @bolt-twig-renderer`. Not sure if the docs should be updated or if this is a bug.

**Comment by sghoweri** [comment]
Hey thanks @a-fro! 

Just confirming — are you just seeing that missing `@bolt/twig-renderer` error in the Drupal Lab theme? If so, could you take a peek to see if the dependencies in the `package.json` are pointing to Bolt v2.3.0 or greater (`@bolt/build-tools` especially)?

I’m suspecting that the dependency versions in our example integrations folder aren’t getting version bumped by Lerna but figure that’d be the most logical thing to check first

**Comment by a-fro** [comment]
Yes, in the bolt-starter theme. I just reproduced by cloning bolt to a new folder, cd'ing into the drupal-lab folder and running `composer run setup`. 

The error above appeared, but I saw this additional output during that process:

```
[1/4] Resolving packages...
warning @bolt/build-tools > @bolt/postcss-themify > @bolt/core > @polymer/lit-element@0.6.2: @polymer/lit-element has moved to lit-element. Please uninstall this package and install lit-element. See https://www.polymer-project.org/blog/2019-01-11-lit-element-rc
warning @bolt/build-tools > sassdoc > sassdoc-theme-default > swig@1.4.0: This package is no longer maintained
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @bolt/build-tools@2.3.0" has unmet peer dependency "@bolt/twig-renderer@^2.3.0-rc.0".
warning "@bolt/build-tools > babel-loader@8.0.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "@bolt/build-tools > eslint-loader@2.1.2" has unmet peer dependency "eslint@>=1.6.0 <6.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 311.56s.

> @bolt/bolt-starter@2.2.2 build /Users/Shared/src/bolt/example-integrations/drupal-lab/web/themes/bolt-starter
> bolt build --prod


    ///////|\\\\\\
   ///˜˜˜˜/|˜˜˜˜\\\
  ///    //|     \\\     Bolt-CLI
 ///    ///|____  \\\
///    /////////   \\\   Welcome to the Bolt CLI ⚡️  Have fun!
\\\   /////////    ///
 \\\      |///    ///    Usage: `bolt <command> [options ...]`
  \\\     |//    ///     Help: `bolt --help` or `bolt <command> --help`
   \\\____|/____///
    \\\\\\|///////

Starting build (serial)
Verbosity: 1
Prod: true
i18n: true
(node:73488) UnhandledPromiseRejectionWarning: Error: Cannot find module '@bolt/twig-renderer'
...
```

The [package.json](https://github.com/bolt-design-system/bolt/blob/master/example-integrations/drupal-lab/web/themes/bolt-starter/package.json) calls for `"@bolt/build-tools": "^2.2.2",` and the yarn.lock that gets generated includes: 

```
"@bolt/build-tools@^2.2.2":
  version "2.3.0"
  resolved "https://registry.yarnpkg.com/@bolt/build-tools/-/build-tools-2.3.0.tgz#2b197e723bbf467a8832814f22e7d01f885893f4"
  integrity sha512-cYmBNx3zL3AlFck0Za9P+ohiQRV+4oxrYJphxS7TVaS+7AuoRHm6ZQ2hzvJ6QSK57aiydEXsMDk8DEiOW8muow==
  dependencies:
    "@bolt/babel-preset-bolt" "^2.3.0"
    "@bolt/config-browserlist" "^2.3.0"
    "@bolt/postcss-themify" "^2.3.0"
    "@bolt/sass-export-data" "^2.3.0"
    "@bolt/sassdoc-webpack-plugin" "^2.3.0"
    "@octokit/plugin-throttling" "^2.3.0"
    "@octokit/rest" "^16.13.3"
    address "^1.0.3"
    autoprefixer "^9.4.3"
    babel-loader "^8.0.4"
    browser-sync "^2.26.3"
    chalk "^2.4.1"
    check-links "^1.1.4"
    chokidar "^2.0.4"
    clean-css-loader "^1.1.0"
    commander "^2.19.0"
    convert-hrtime "^2.0.0"
    copy-webpack-plugin "^4.6.0"
    cosmiconfig "^5.0.7"
    css-hot-loader "^1.4.3"
    css-loader "^2.0.2"
    deepmerge "^3.0.0"
    del "^3.0.0"
    eslint-loader "^2.1.1"
    execa "^1.0.0"
    express "^4.16.4"
    file-loader "^3.0.1"
    front-matter "^3.0.1"
    globby "^8.0.1"
    hard-source-webpack-plugin-patch "^0.13.3"
    incache "^7.2.1"
    js-yaml "^3.12.0"
    json-loader "^0.5.7"
    jsonschema "^1.2.4"
    lodash.debounce "^4.0.8"
    marked "^0.5.2"
    mini-css-extract-plugin "^0.5.0"
    mkdirp "^0.5.1"
    node-cache "^4.2.0"
    node-fetch "^2.3.0"
    node-notifier "^5.3.0"
    node-sass "^4.11.0"
    npm-sass "^2.3.0"
    optimize-css-assets-webpack-plugin "^5.0.1"
    ora "^3.0.0"
    portfinder "^1.0.20"
    postcss-discard-duplicates "^4.0.2"
    postcss-loader "^3.0.0"
    postcss-scss "^2.0.0"
    pretty-ms "^4.0.0"
    resolve "^1.9.0"
    resolve-url-loader "^3.0.0"
    sass-loader "^7.1.0"
    sassdoc "^2.5.1"
    semver "^5.6.0"
    sharp "^0.21.3"
    string-replace-loader "^2.1.1"
    style-loader "^0.23.1"
    svgo "^1.1.1"
    ts-loader "^5.3.2"
    typescript "^3.2.2"
    uglifyjs-webpack-plugin "^2.1.0"
    url-loader "^1.1.2"
    webpack "4.28.2"
    webpack-cli "^3.1.2"
    webpack-dev-middleware "^3.4.0"
    webpack-hot-middleware "^2.24.3"
    webpack-manifest-plugin "^2.0.4"
    write-file-webpack-plugin "^4.5.0"
    yaml-loader "^0.5.0"
    yargs "^12.0.5"
...
```

Hope that's helpful.
